export const comprod = [
  {
    id: 1,
    compName: '7Green Grows Inc.',
    compWebSite: 'https://www.7green.ca/about-us',
    prodName: 'Dried Flower',
  },
  {
    id: 2,
    compName: '7Green Grows Inc.',
    compWebSite: 'https://www.7green.ca/about-us',
    prodName: 'Terpenes',
  },
  {
    id: 3,
    compName: 'Aphria',
    compWebSite: 'https://www.aphria.ca',
    prodName: 'Oils',
  },
  {
    id: 4,
    compName: 'Aphria',
    compWebSite: 'https://www.aphria.ca',
    prodName: 'Softgels & Capsules',
  },
  {
    id: 5,
    compName: 'Aphria',
    compWebSite: 'https://www.aphria.ca',
    prodName: 'Oral Spray',
  },
  {
    id: 6,
    compName: 'Aphria',
    compWebSite: 'https://www.aphria.ca',
    prodName: 'Vapes',
  },
  {
    id: 7,
    compName: 'Aphria',
    compWebSite: 'https://www.aphria.ca',
    prodName: 'Dried Flower',
  },
  {
    id: 8,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Oils',
  },
  {
    id: 9,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Edibles',
    },
  {
    id: 10,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Concentrates',
  },
  {
    id: 11,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Vapes',
  },
  {
    id: 12,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Dried Flower',
  },
  {
    id: 13,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Preroll',
  },
  {
    id: 14,
    compName: 'Aqualitas Inc.',
    compWebSite: 'https://www.aqualitas.ca',
    prodName: 'Terpenes',
  },
  {
    id: 15,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Oils',
  },
  {
    id: 16,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Softgels & Capsules',
  },
  {
    id: 17,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Oral Spray',
  },
  {
    id: 18,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Edibles',
  },
  {
    id: 18,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Concentrates',
  },
  {
    id: 19,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Vapes',
  },
  {
    id: 20,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Vapes',
  },
  {
    id: 21,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Dried Flower',
  },
  {
    id: 22,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Preroll',
  },
  {
    id: 23,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Terpenes',
  },
  {
    id: 24,
    compName: 'Aurora Medical',
    compWebSite: 'https://www.auroramedical.com/collections/all/',
    prodName: 'Accessories',
  }
];
